---

- name: common | update apt-cache
  apt: update_cache=yes cache_valid_time=3600
  tags:
    - common_install

- name: common | upgrade the distro
  apt: upgrade=yes
  tags:
    - common_install

- name: common | install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - git
    - curl
    - zip
    - unzip
    - wget
  tags:
    - common_install

- name: create locale
  locale_gen: name={{ app_locale }} state=present
  tags:
    - common_install
    - common_install_locale

- name: set default locale
  command: "/usr/sbin/update-locale LANG={{ app_locale }}"
  tags:
    - common_install
    - common_install_locale

- name: common | create admin group
  group: name=admin state=present
  tags:
    - common_user

- name: common | create app user group
  group: name={{ app_user }} state=present
  tags:
    - common_user

- name: common | create user
  user: name="{{ app_user }}"
        groups=admin,{{ app_user }}
        home="{{ app_user_home }}"
        shell=/bin/bash
        state=present
  tags:
    - common_user

- name: common | add ssh key
  authorized_key: user={{ app_user}}
                  key="{{ lookup('file', 'public_keys/hlm.pub') }}"
  tags:
    - common_user

- name: common | add admin group to sudoers
  lineinfile: dest=/etc/sudoers state=present
              regexp='^%ADMIN ALL\='
              line='%ADMIN ALL=(ALL) NOPASSWD:ALL'
              validate='visudo -cf %s'
  tags:
    - common_user
