---

dependencies:
  - role: zzet.rbenv
    rbenv:
      env: user
      version: v0.4.0
      ruby_version: 2.1.2
    rbenv_users:
      - { name: "{{ app_user }}", home: "{{ app_user_home }}" }
    sudo: yes
