development:
  # Configure available database sessions. (required)
  sessions:
    default:
      database: hlm_development
      hosts:
        - db:27017

test:
  sessions:
    default:
      database: hlm_test
      hosts:
        - db:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      uri: <%= ENV['MONGOID_URI'] %>

