#!/usr/bin/env ruby
#^syntax detection

forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt'

mod 'attachmentgenie/locales', '1.0.3'
mod 'puppetlabs/java', '1.1.0'
mod 'torrancew/account', '0.0.5'
mod 'alup/rbenv', '1.2.0'
mod 'puppetlabs/mongodb', '0.7.0'
mod 'elasticsearch/elasticsearch', '0.3.1'
